# Generated by Django 2.2.5 on 2020-03-13 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token_for_bot',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
